### ISSUE TITLE
missing trial.dpreg

### ISSUE THREAD

**Issue by mschebella** [diablodale/dp.kinect3#3]
## Description

Hi, I downloaded the dp.kinect3 plugin from
https://hidale.com/wp-content/uploads/2020/08/dp.kinect3-v1.3.20220321.zip
It seems the package does not contain a trial.dpreg file, which I think I need to test the plugin. Sorry, if I miss something obvious here.

## Setup

Microsoft Surface Book Pro with Windows 10 Pro
Azure Kinect SDK 1.4.1
Max 8.1.11
dp.kinect3 v1.3.20220321

## Steps to reproduce

I copied the unzipped folder to Documents/Max 8/library
then opened the dp.kinect3.maxhelp
Console sais:
dp.kinect3 dp.kinect3 is not registered or has expired.  RG:33554464 RV:0
dp.kinect3 is not registered or has expired. Register your key or visit https://hidale.com for purchase and support.

then I go to the register tab and click on "register trial" and console output sais
dp.kinect3: Registration file not found

I looked into the folders and did not see the trial.dpreg, which I assume should be there(?)

best regards

**Comment by diablodale** [comment]
You are correct, it was missing. Thank you for opening this issue.
I have updated the download and it is ready at https://hidale.com/shop/dp-kinect3/
I will also correct my build system so this doesn't happen again.

Thank you, and happy patching! :-)
