### ISSUE TITLE
Body Tracking SDK 1.1.1 breaks "Failed to create k4abt tracker"

### ISSUE THREAD

**Issue by mschebella** [diablodale/dp.kinect3#4]
## Description
Hi, 
I ran into another problem with the plugin. When I try to run the body joints patch, the console spits out:
dp.kinect3: Error opening 000202302712 sensor: Failed to create k4abt tracker!

## Setup
I'm on a Windows 10 Pro System
Microsoft Surface Book Pro 
Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz
NVIDIA Quadro RTX 3000

I installed the dp.kinect3 in my Max Application folder (resources/packages)
I also copied all mentioned files from the SDK/tools into the dp.kinect3 package folder. 

Azure Kinect SDK 1.4.1
Azure Kinect Body Tracking SDK 1.1.1.msi
dp.kinect3-v1.3.20220321
max 8.1.11

## Steps to reproduce

I am starting the dp.kinect3.maxhelp (trial version is registered) and on the first tab, the depth and color image ar shown properly. I am sending a close message to the object and switch to the third tab (body joints). 

when I klick on the toggle to start, there is an error message in the console
dp.kinect3: Error opening 000202302712 sensor: Failed to create k4abt tracker!

I don't think any files are missing, I even added the paths of Azure Kindect SDK and Azure Kinect Body Tracking SDK to the max preferences. I also turned on verbose mode, but no further messages.

With theAzure Kinect Body tracking SDK comes a 3d viewer app which, when run, shows the depth image and joints, so the hardware seems to work correctly (although slowly with a low framerate).

I have not worked with the Kinect SDK yet, like in Visual Studio, so there might still be some files or paths missing or something is not compatible with the dp.kinect3 binaries, but that's just a wild guess.

best regards.

**Comment by diablodale** [comment]
I recommend using Body Tracking v1.1.0 for now https://docs.microsoft.com/en-us/azure/kinect-dk/body-sdk-download#windows-download-links

You and one other customer have reported issues with Body Tracking v1.1.1. I suspect this is a Microsoft code fault with it.
In late May, I will turn my attention to that new SDK and see what Microsoft broke so I can report the problem to them and/or make needed changes to dp.kinect3.

**Comment by mschebella** [comment]
thank you! switching to v1.1.0 worked.
