### ISSUE TITLE
dp.kinect3: Error opening 000077702912 sensor: Failed to create k4abt tracker!

### ISSUE THREAD

**Issue by studiosalamero** [diablodale/dp.kinect3#5]
Hi Dale, I am going through the dp.kinect help file and am unable to get the body joints example working.

When I click the open object, the console returns:
dp.kinect3: Error opening 000077702912 sensor: Failed to create k4abt tracker!

I've added @verbrose 1 to the patch and it still shows the exact same error message

---

**My Hardware**
Device name	MSI
Processor	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.20 GHz
Installed RAM	16.0 GB (15.8 GB usable)
Device ID	EDC3D130-72CC-4C68-9FFA-2DE643866804
Product ID	00325-80183-21071-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Windows specifications**
Edition	Windows 10 Home
Version	21H2
Installed on	‎4/‎1/‎2022
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

MAX version 8.2.2 (85d93eb32e9) (x64 windows), registered

dp.kinect3 version: dp.kinect3-v1.3.20220321

![image](https://user-images.githubusercontent.com/104850022/166497434-bc02c07f-7468-4341-86d6-e01cab654790.png)

```

**Comment by diablodale** [comment]
I suspect the body tracking part of setup wasn't completed; same as issues #4 or #2
Please closely follow https://github.com/diablodale/dp.kinect3/wiki#body-tracking-setup

**Comment by diablodale** [comment]
closing, customer has no update.
