### ISSUE TITLE
Add support for Wide FOV

### ISSUE THREAD

**Issue by andrea-efferao** [diablodale/dp.kinect3#8]
One of the most useful feature of the azure kinect compared to the previous versions is the wide angle camera, also for body tracking.

would you consider supporting in your project?

Thank you

**Comment by diablodale** [comment]
Hello. dp.kinect3 already supports wide-angle depth. 
https://docs.hidale.com/max/attributes/depthmapres controls the resolution modes of the depth sensor.

**Comment by andrea-efferao** [comment]
Thank you! I missed that scrolling through the docs.
